# Homebrew formula for cqlsh-rs.
#
# This repository doubles as its own Homebrew tap — there is no separate
# `scylladb/homebrew-cqlsh-rs` repository, so the tap must be added with an
# explicit URL:
#
#   brew tap scylladb/cqlsh-rs https://github.com/scylladb/cqlsh-rs
#   brew install cqlsh-rs
#
# The `version`, `url` and `sha256` fields are rewritten automatically after
# every release by the `update-homebrew-formula` job in
# .github/workflows/ci.yml. To refresh them by hand:
#
#   python3 scripts/update_homebrew_formula.py 0.5.13
#
# CI installs and tests this formula on macOS — see .github/workflows/homebrew.yml.

class CqlshRs < Formula
  desc "Rust re-implementation of the Cassandra cqlsh CQL shell"
  homepage "https://github.com/scylladb/cqlsh-rs"
  version "0.5.13"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/scylladb/cqlsh-rs/releases/download/v0.5.13/cqlsh-rs-0.5.13-aarch64-apple-darwin.tar.gz"
      sha256 "7d3f727462c5aa1b919ec3ec53103066e6e128c34c64f1232f40190412be6069"
    end

    on_intel do
      url "https://github.com/scylladb/cqlsh-rs/releases/download/v0.5.13/cqlsh-rs-0.5.13-x86_64-apple-darwin.tar.gz"
      sha256 "821a0cfe47061841355226152f209db22169bad4f4d8f251b970ef776909a71f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/scylladb/cqlsh-rs/releases/download/v0.5.13/cqlsh-rs-0.5.13-aarch64-unknown-linux-musl.tar.gz"
      sha256 "d89a80cf10a8f3222c79ea5ac9c1a7d7115529b3f51333828924a67757762625"
    end

    on_intel do
      url "https://github.com/scylladb/cqlsh-rs/releases/download/v0.5.13/cqlsh-rs-0.5.13-x86_64-unknown-linux-musl.tar.gz"
      sha256 "93f8623b0c4fea9579c398ff5d13fae813c19e0676c7fe01d404d749f80bceed"
    end
  end

  def install
    bin.install "cqlsh-rs"

    # The release archives ship only the binary; the man page and shell
    # completions are generated by the binary itself.
    (man1/"cqlsh-rs.1").write Utils.safe_popen_read(bin/"cqlsh-rs", "--generate-man")
    generate_completions_from_executable(bin/"cqlsh-rs", "--completions")
  end

  test do
    # `--version` reports the Python-cqlsh-compatible program name ("cqlsh"),
    # not the binary name.
    assert_match "cqlsh #{version}", shell_output("#{bin}/cqlsh-rs --version")

    # Connecting to a closed port must fail with cqlsh's exit code 2 and a
    # Python-cqlsh-compatible error message, not a panic.
    output = shell_output("#{bin}/cqlsh-rs 127.0.0.1 1 -e 'SELECT now() FROM system.local' 2>&1", 2)
    assert_match "Unable to connect to any servers", output
  end
end
