# Homebrew formula for cqlsh-rs.
#
# This repository doubles as its own Homebrew tap — there is no separate
# `scylladb/homebrew-cqlsh-rs` repository, so the tap must be added with an
# explicit URL:
#
#   brew tap scylladb/cqlsh-rs https://github.com/scylladb/cqlsh-rs
#   brew install cqlsh-rs
#
# The `url` and `sha256` fields are rewritten automatically after every release
# by the "Update Homebrew formula" step of the release pipeline in
# .github/workflows/ci.yml. To refresh them by hand:
#
#   python3 scripts/update_homebrew_formula.py 0.5.13
#
# The version is deliberately not declared: Homebrew scans it from the release
# URL, and `brew audit --strict` rejects a redundant `version` line.
#
# CI installs and tests this formula on macOS — see .github/workflows/homebrew.yml.

class CqlshRs < Formula
  desc "Rust re-implementation of the Cassandra cqlsh CQL shell"
  homepage "https://github.com/scylladb/cqlsh-rs"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/scylladb/cqlsh-rs/releases/download/v0.5.17/cqlsh-rs-0.5.17-aarch64-apple-darwin.tar.gz"
      sha256 "f7c5a622cd22dc4b6b38ca4085e1e65547b853c9435af2fb3bd1094803677a7d"
    end

    on_intel do
      url "https://github.com/scylladb/cqlsh-rs/releases/download/v0.5.17/cqlsh-rs-0.5.17-x86_64-apple-darwin.tar.gz"
      sha256 "503d1f5caecbc9d5cf4dace2ce331538fee02a8999199b05f25f29db6e18929a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/scylladb/cqlsh-rs/releases/download/v0.5.17/cqlsh-rs-0.5.17-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4f669abd9ab700ee7a682e31903b40ab0a7d382939d6c0077c3e7618634bcf39"
    end

    on_intel do
      url "https://github.com/scylladb/cqlsh-rs/releases/download/v0.5.17/cqlsh-rs-0.5.17-x86_64-unknown-linux-musl.tar.gz"
      sha256 "c17bb3d1ce8d6100956d64e27572d77358d3bb4eee854187664f6cca3a9e72e6"
    end
  end

  def install
    bin.install "cqlsh-rs"

    # The release archives ship only the binary; the man page and shell
    # completions are generated by the binary itself.
    (man1/"cqlsh-rs.1").write Utils.safe_popen_read(bin/"cqlsh-rs", "--generate-man")
    generate_completions_from_executable(bin/"cqlsh-rs", "--completions")
  end

  test do
    # `--version` reports the Python-cqlsh-compatible program name ("cqlsh"),
    # not the binary name.
    assert_match "cqlsh #{version}", shell_output("#{bin}/cqlsh-rs --version")

    # Connecting to a closed port must fail with cqlsh's exit code 2 and a
    # Python-cqlsh-compatible error message, not a panic.
    output = shell_output("#{bin}/cqlsh-rs 127.0.0.1 1 -e 'SELECT now() FROM system.local' 2>&1", 2)
    assert_match "Unable to connect to any servers", output
  end
end
