# Homebrew formula for cqlsh-rs.
#
# This repository doubles as its own Homebrew tap — there is no separate
# `scylladb/homebrew-cqlsh-rs` repository, so the tap must be added with an
# explicit URL:
#
#   brew tap scylladb/cqlsh-rs https://github.com/scylladb/cqlsh-rs
#   brew install cqlsh-rs
#
# The `url` and `sha256` fields are rewritten automatically after every release
# by the "Update Homebrew formula" step of the release pipeline in
# .github/workflows/ci.yml. To refresh them by hand:
#
#   python3 scripts/update_homebrew_formula.py 0.5.13
#
# The version is deliberately not declared: Homebrew scans it from the release
# URL, and `brew audit --strict` rejects a redundant `version` line.
#
# CI installs and tests this formula on macOS — see .github/workflows/homebrew.yml.

class CqlshRs < Formula
  desc "Rust re-implementation of the Cassandra cqlsh CQL shell"
  homepage "https://github.com/scylladb/cqlsh-rs"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/scylladb/cqlsh-rs/releases/download/v0.5.16/cqlsh-rs-0.5.16-aarch64-apple-darwin.tar.gz"
      sha256 "d49fee2c746bb8cfd036b563a3a79ff8482599528605b620c625083f6625f3e7"
    end

    on_intel do
      url "https://github.com/scylladb/cqlsh-rs/releases/download/v0.5.16/cqlsh-rs-0.5.16-x86_64-apple-darwin.tar.gz"
      sha256 "ae8d80155c65386e8f9f29c0f11796b10d6d4880cbac927cc4cc6a80795531b6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/scylladb/cqlsh-rs/releases/download/v0.5.16/cqlsh-rs-0.5.16-aarch64-unknown-linux-musl.tar.gz"
      sha256 "3a994058d9e98c28220056e7f0b936525e51be2fe2505ac36b4622e30bb76c37"
    end

    on_intel do
      url "https://github.com/scylladb/cqlsh-rs/releases/download/v0.5.16/cqlsh-rs-0.5.16-x86_64-unknown-linux-musl.tar.gz"
      sha256 "32d688414ca11c8d6c946e63d7aa4bb4cf60dba35281bcd873ea5c591dee9cb8"
    end
  end

  def install
    bin.install "cqlsh-rs"

    # The release archives ship only the binary; the man page and shell
    # completions are generated by the binary itself.
    (man1/"cqlsh-rs.1").write Utils.safe_popen_read(bin/"cqlsh-rs", "--generate-man")
    generate_completions_from_executable(bin/"cqlsh-rs", "--completions")
  end

  test do
    # `--version` reports the Python-cqlsh-compatible program name ("cqlsh"),
    # not the binary name.
    assert_match "cqlsh #{version}", shell_output("#{bin}/cqlsh-rs --version")

    # Connecting to a closed port must fail with cqlsh's exit code 2 and a
    # Python-cqlsh-compatible error message, not a panic.
    output = shell_output("#{bin}/cqlsh-rs 127.0.0.1 1 -e 'SELECT now() FROM system.local' 2>&1", 2)
    assert_match "Unable to connect to any servers", output
  end
end
